CREATE TABLE CustomerAccessLog(
    CUSTOMERID VARCHAR(36) NOT NULL,
    USERNAME VARCHAR(20),
    LOGINTIME TIMESTAMP,
    LOGOUTTIME TIMESTAMP,
    FOREIGN KEY (CUSTOMERID) REFERENCES Customer(CUSTOMERID)
);

     