CREATE TABLE CustomerOrder(
    ORDERID VARCHAR(36) NOT NULL PRIMARY KEY,
    CUSTOMERID VARCHAR(36) NOT NULL,
    PRODUCTID VARCHAR(36) NOT NULL,
    ORDERDATE TIMESTAMP,
    QUANTITY INT,
    TOTALPRICE DECIMAL(10, 2)

);