CREATE TABLE Staff (
    StAFFID VARCHAR(36) NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(20) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
   
    GMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL,
    PHONE VARCHAR(10) NOT NULL,
     GENDER VARCHAR(8) NOT NULL
);