CREATE TABLE StaffAccessLog(
    LOGID VARCHAR(36) PRIMARY KEY,
    StaffID VARCHAR(36) NOT NULL,
    USERNAME VARCHAR(20),
    LOGINTIME TIMESTAMP,
    LOGOUTTIME TIMESTAMP,
    FOREIGN KEY (STAFFID) REFERENCES Staff(STAFFID)
);
